language: php

php:
    - 7.1
    - 7.2
    - 7.3

before_script:
    - composer install --dev --prefer-source
    - if [ -f $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini ]; then phpenv config-rm xdebug.ini; fi

script:
    - vendor/bin/phpstan.phar analyse -c phpstan.neon --level 7 .
    - vendor/phpunit/phpunit/phpunit

notifications:
  email: "douglas@usemarkup.com"

dist: trusty
sudo: required
